<?php

use Symfony\Component\Config\Definition\Configurator\DefinitionConfigurator;

return static function (DefinitionConfigurator $definition): void {
    $definition
        ->rootNode()
            ->addDefaultsIfNotSet()
            ->children()
                ->arrayNode('operation')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('controller')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('suffix')->defaultValue('Action')->end()
                            ->end()
                        ->end()
                        ->arrayNode('request')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('write_only')->defaultTrue()->end()
                                ->scalarNode('suffix')->defaultValue('Body')->end()
                            ->end()
                        ->end()
                        ->arrayNode('response')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('read_only')->defaultTrue()->end()
                                ->scalarNode('suffix')->defaultValue('View')->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('paths')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('controller')->defaultValue('<resource>/Controller/<method>/')->end()
                        ->scalarNode('request')->defaultValue('<resource>/Controller/<method>/')->end()
                        ->scalarNode('response')->defaultValue('<resource>/Controller/<method>/')->end()
                    ->end()
                ->end()
            ->end()
        ->end()
    ;
};
